version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: game-characters-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_characters
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: game-characters-server
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: game_characters
      JWT_SECRET: seu_segredo_jwt_super_secreto
      PORT: 5000
      NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: game-characters-client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5000
      - WDS_SOCKET_PORT=0

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 